version: '{branch}.ci.{build}'
init:
- ps: Update-AppveyorBuild -Version "$env:appveyor_repo_branch.$(Get-Date -format yyyy.MM.dd).$env:appveyor_build_number"

os:
- Visual Studio 2017

configuration:
- Debug
- Release

platform:
- Win32

branches:
  except:
    - coverity_scan

environment:
  ASIO_STANDALONE: 1
  MYSQL_DATABASE: osirose
  MYSQL_HOST: localhost
  MYSQL_USER: root
  MYSQL_PWD: "Password12!"
  MYSQL_PATH: C:\Program Files\MySQL\MySQL Server 5.7
  MYSQL_CONNECTOR_PATH: C:\Program Files (x86)\MySQL\MySQL Connector C 6.1
  PROJECT_PATH: C:\projects\osIROSE
  GTEST_OUTPUT: C:\projects\osIROSE\build\Test.xml
  PYTHON_PATH: C:\Python35
  INCLUDE: C:\projects\osIROSE\3rdparty\googletest\googlemock\include;C:\projects\osIROSE\3rdparty\googletest\googletest\include;C:\projects\osIROSE\3rdparty\spdlog\include;

matrix:
  fast_finish: true

clone_depth: 50
clone_folder: C:\projects\osIROSE
services: mysql

install:
- cmd: cd %PROJECT_PATH%
- ps: Start-FileDownload http://dev.mysql.com/get/Downloads/Connector-C/mysql-connector-c-6.1.11-win32.msi -FileName C:\projects\osIROSE\mysql-connector-c-winx32.msi
- cmd: git submodule update --init --recursive
- cmd: "./cmake/scripts/msvc_mysqlpp_install.bat"
- cmd: "./cmake/scripts/msvc_install.bat"

build:
  parallel: true

build_script:
- cd build
- cmake -D%CONFIGURATION%=TRUE -DCMAKE_BUILD_TYPE=%CONFIGURATION% ..
- cmake --build . --clean-first --config %CONFIGURATION% -- /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
- cp "%MYSQL_CONNECTOR_PATH%\lib\libmysql.dll" "%PROJECT_PATH%\build\bin\%CONFIGURATION%
- 7z a %APPVEYOR_BUILD_FOLDER%/win32-%APPVEYOR_BUILD_VERSION%-%CONFIGURATION%.zip %APPVEYOR_BUILD_FOLDER%/build/bin/ %APPVEYOR_BUILD_FOLDER%/Database

artifacts:
- path: win32-$(appveyor_build_version)-$(configuration).zip
  name: osirose-package

notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  auth_token:
    secure: QRzsk64PSFoDEGoTiL44n9yIlkyCrY/cG2HW5hVDIlVNdkW/m47qgyjTeBR4ri5+PmYwVxelkdOipzJBeTVRSsciTo2aGnk4QHXyRyR4Nra6SAxaDuKFUC3Sbc8jXnmq
  channel: osirose-commits
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false

before_test:
  - SET PATH=%MYSQL_CONNECTOR_PATH%\lib;%MYSQL_PATH%\bin;%PYTHON_PATH%\Scripts;%PATH%
  - SET STATIC_DEPS=true
  - pip.exe install lxml
  - mysqladmin --host=%MYSQL_HOST% --user=%MYSQL_USER% --password=%MYSQL_PWD% create %MYSQL_DATABASE%
  - mysql --user=%MYSQL_USER% --password=%MYSQL_PWD% --database=%MYSQL_DATABASE% < "%PROJECT_PATH%/Database/osirose.sql"
  - C:/projects/osIROSE/build/bin/%CONFIGURATION%/TestConfig.exe --gtest_filter=SetupTesting.**
  - ps: $a = Get-Content 'C:\projects\osIROSE\build\server.json' -raw | ConvertFrom-Json; $a.database | % {if($_.user -eq 'root'){$_.password='Password12!'}}; $a | ConvertTo-Json  | set-content 'C:\projects\osIROSE\build\server.json'; $a | ConvertTo-Json  | set-content 'C:\projects\osIROSE\build\test.ini'; $a | ConvertTo-Json  | set-content 'C:\projects\osIROSE\build\src\tests\server.json'; $a | ConvertTo-Json  | set-content 'C:\projects\osIROSE\build\src\tests\test.ini';

test_script:
  - ctest -C %CONFIGURATION% --output-on-failure --no-compress-output -T Test -E "TestConfig|SetupTesting" || verify > NUL

#deploy:
#  release: osirose-win-v$(appveyor_build_version) # this is here to prevent appveyor from overwriting our release notes
#  description: ''
#  provider: GitHub
#  auth_token:
#    secure: g7E2KwFd5bLd1ZiWSFGE9Ek13/uDOmmsOh080SXDBYcIpbL/rXHOU53F7t3ZxpmS # your encrypted token from GitHub
#  artifact: osirose-package
#  draft: true
#  prerelease: true
#  force_update: false
#  on:
#    branch: master                 # release from master branch only
#    appveyor_repo_tag: true        # deploy on tag push only


#init:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
